services:
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo-db'
    environment:
    - 'MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}'
    - 'MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo_data:/data/db'
volumes:
  mongo_data: